nginx:
  build: ./nginx
  links:
    - web:web
  ports:
    - "80:80"
db:
  image: mongo
  ports:
    - "27017:27017"
  restart: always
web:
  build: .
  command: npm run dev
  volumes:
    - ./:/var/www/app/current/
    - /var/www/app/current/node_modules
  ports:
    - "3000"
  
  links:
    - db
  #  